spring.application.name=crudCharacters
# Configura\uFFFD\uFFFDo do MongoDB
spring.data.mongodb.uri=mongodb+srv://solo-rpg-user:12345@solo-rpg-cluster.a9foahc.mongodb.net/?retryWrites=true&w=majority&appName=solo-rpg-cluster
spring.data.mongodb.database=solo_rpg
server.port=8002