spring.application.name=crudCharacters
server.port=8002

spring.data.mongodb.uri=mongodb+srv://solo-rpg-user:12345@solo-rpg-cluster.a9foahc.mongodb.net/solo_rpg?retryWrites=true&w=majority

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
application.security.jwt.expiration=86400000

spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.exposed-headers=Authorization